### ISSUE TITLE
Images of the render cannot be accessed by the browser

### ISSUE THREAD

**Issue by Rover17-Dev** [Hebbinkpro/PocketMap#10]
![image](https://github.com/Hebbinkpro/PocketMap/assets/74236531/47198ec8-16b2-4413-b29d-10b5f8a9d1ec)
Hello
A new bug is occurring on the servers running under Pterodactyl Panel environment 
The worlds are successfully rendered, but the image cannot be accessed by the browser and the image files are returning a 404 File not found error. I tried this in 2 different servers from different host and 3 different browsers, and it is doing the same thing. 
And I check in the render and this files exist. I think that maybe the file location is rong or that the api have a bug.

![image](https://github.com/Hebbinkpro/PocketMap/assets/74236531/a3ae8c77-2bfd-43c3-b8c1-e2abf2fc98d8)

Thank you for your plugin.

**Comment by Rover17-Dev** [comment]
The render is successfully finished, and this bug didn't occur in the previous version before 0.3

**Comment by Hebbinkpro** [comment]
Hi, that's weird because for me it's working on windows and on a Pterodactyl panel.

Maybe the issue is that you don't have a world with `world` as a folder name, currently only that world is displayed because I've yet to implement support for multiple worlds.

If this is the problem, you can easily fix it by changing something in line 14 of `web/static/script/main.js`
```js
L.tileLayer(API_URL + "render/world/{z}/{x},{y}.png", {...
```
Change `world` in the name of the world you want to display. Same for the `"world"` at line 104 in the same file if you want to show the online players in that world.

If this is not the problem, then something else is going on.

**Comment by Rover17-Dev** [comment]
Thank you very much
Finally, after all this issues, the plugin works properly on my server.
I am sorry if I had been annoying with all that, and thank you a lot.

**Comment by Hebbinkpro** [comment]
Great! Your feedback and bug reporting was very helpful.
