### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by DevPapo** [Hebbinkpro/PocketMap#34]
if (!PacketHooker::isRegistered()) {
    PacketHooker::register($this);
}

In PocketMap.php

I don't know what's going on, it's like the plugin doesn't install composer. Or do I need a plugin or some other dependency for it to work?

This error appears in Crashdumps:
![Screenshot_20241124_224944_Chrome](https://github.com/user-attachments/assets/c061f32f-3fcf-4f0c-aa40-0aefcd90dde2)

**Comment by Hebbinkpro** [comment]
Hi,

The plugin should not be used as a folder plugin, since the composer files in the vendor folder will not be included.

If you just want to use the plugin, download the phar from [poggit](https://poggit.pmmp.io/ci/Hebbinkpro/PocketMap).

If you want to run the plugin from source, use [Pharynx](https://github.com/SOF3/pharynx), this will create a phar of the source and makes sure all the required packages are included.
