### ISSUE TITLE
Render not loaded in google

### ISSUE THREAD

**Issue by Rover17-Dev** [Hebbinkpro/PocketMap#9]
Hello
My world is rendering for about 30 minutes now
And I can see the images been generated in the render files 
But when I open the website it is impossible to load, and it didn't do that 
In addition, my world is very small 

![image](https://github.com/Hebbinkpro/PocketMap/assets/74236531/ebe331a8-b1eb-4ad7-9d84-c2d6edbba4f6)
![screen](https://github.com/Hebbinkpro/PocketMap/assets/74236531/464784ee-8cd2-41e6-a91c-5de3e3c1f206)

Thank you for your plugin

**Comment by Hebbinkpro** [comment]
It can take a while until all chunks of your world are rendered into images. The map also has different zoom levels, you can change the zoom level by zooming in in or out.
It looks like that the images for zoom level -3 (very zoomed out) are not yet generated.

If you look in your plugin data under the renders, you can see which images for which zoom levels are generated.

You can ignore the 404 errors in the web console, because leaflet will always try to request the images, for the case they will be there, thats why you get so  many of those errors.
